version: '3.9'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - 5432:5432
    restart: on-failure
